export const PRODUCTION_ORDER_LABELS = {
  listTitle: "Orden de producción",
  listSubtitle: "Órdenes comerciales antes de programación en planta.",
  newOrder: "Nueva",
  newClient: "Nuevo cliente",
  newProduct: "Nuevo producto",
  createClientHint: "¿No aparece el cliente? Regístrelo sin salir del flujo de órdenes.",
  createProductHint: "¿No aparece el producto? Regístrelo para el cliente seleccionado.",
  mastersCalloutTitle: "¿Cliente o producto nuevo?",
  mastersCalloutBody:
    "Use el menú Órdenes o los botones de abajo para registrar clientes y productos. Al guardar, vuelve automáticamente a la orden.",
  formTitleNew: "Nueva orden",
  formTitleEdit: "Editar orden",
  formSubtitle: "Cliente, fecha e ítems antes de programación en planta.",
  formHelp:
    "Registre el cliente, la referencia comercial y los productos solicitados. Al guardar, la orden pasará a Programación para asignar máquinas y fechas.",
  formFooterHint: "Cliente y al menos un ítem con cantidad son obligatorios.",
  formFooterNew: "Al guardar, la orden aparecerá en Programación.",
  formFooterEdit: "Actualice los datos de la orden comercial.",
  searchPlaceholder: "Código, cliente o producto",
  searchAriaLabel: "Buscar órdenes por código, cliente o producto",
  loadError: "No se pudieron cargar las órdenes de producción.",
  saveError: "No se pudo guardar la orden de producción.",
  loadOneError: "No se pudo cargar la orden de producción.",
  saved: "Orden de producción guardada.",
  savedGoProgramacion: "Orden creada. Aparecerá en Programación.",
  goToProgramacion: "Ir a Programación",
  cancel: "Volver al listado",
  save: "Guardar orden",
  saving: "Guardando…",
  count: (n: number) => `${n} órden${n === 1 ? "" : "es"}`,
  tabs: {
    all: "Todas",
    awaitingSchedule: "Por programar",
    open: "Abiertas",
    fulfilled: "Cerradas",
  },
  table: {
    number: "N.º",
    actions: "Acciones",
    edit: "Editar",
    history: "Registro",
  },
  historyTitle: (code: string | number) => `Registro de orden ${code}`,
  historySubtitle: "Cómo empezó, solicitudes de almacén, producción y despacho.",
  historyEmpty: "No hay registro disponible para esta orden.",
  historyRequests: "Solicitudes de almacén",
  historyProduction: "Producción (extrusión)",
  historyDispatch: "Despacho de bobinas",
  columns: {
    code: "Código",
    batchCode: "Nº OP",
    client: "Cliente",
    product: "Producto",
    quantity: "Cantidad",
    status: "Estado",
    plant: "En planta",
    actions: "Acciones",
  },
  sections: {
    identity: "Identificación",
    identityHint: "Cliente, venta para y fecha de la orden comercial.",
    order: "Datos de la orden",
    orderHint: "Cliente, venta para y fecha de la orden comercial.",
    notes: "Notas",
    notesHint: "Observaciones internas o instrucciones para producción.",
    lines: "Ítems",
    linesHint: "Productos y cantidades solicitados por el cliente.",
  },
  preview: {
    title: "Vista previa",
    hint: "Esta orden comercial se usará en Programación y en las solicitudes de insumos.",
    noClient: "Sin cliente",
    noLines: "Sin ítems",
    batch: "Nº OP",
  },
  emptyTitle: "Sin órdenes",
  emptyDescription: "Cree la primera orden para iniciar programación y producción.",
  emptyFiltered: "Sin coincidencias",
  emptyFilteredHint: "Pruebe otro código, cliente o producto.",
  scheduleLink: "Programar",
  fields: {
    client: "Cliente",
    saleFor: "Venta para",
    rif: "RIF",
    address: "Dirección",
    orderedAt: "Fecha",
    notes: "Notas",
    status: "Estado",
  },
  saleForPlaceholder: "Destino o referencia comercial",
  clientDataEmpty: "—",
  clientSelect: "Seleccione cliente…",
  productSelect: "Seleccione producto…",
  linesTitle: "Ítems",
  linesClientHint: "Seleccione un cliente para cargar sus productos.",
  linesEmpty: "Agregue al menos una línea de producto.",
  linesTable: {
    item: "Ítem",
    product: "Producto",
    quantity: "Cantidad",
    unit: "Unidad",
    description: "Descripción",
  },
  lineUnits: [
    { value: "kg", label: "Kg" },
    { value: "fardo", label: "Fardo" },
    { value: "unidad", label: "Unidad" },
    { value: "rollo", label: "Rollo" },
  ] as const,
  addLine: "Añadir línea",
  removeLine: "Quitar",
  addToBatchTitle: "Agregar pedido al mismo Nº OP",
  addToBatchSelect: "Filtrar por Nº OP…",
  addToBatchGo: "Agregar pedido",
  addToBatchFilterActive: (code: string) => `Filtrando por ${code}`,
  addToBatchHint: (code: string) => `Se vinculará al Nº OP ${code}. Cada pedido conserva su cliente e ítems.`,
  addAnotherOrder: "Agregar otro pedido",
  lineProduct: "Producto",
  lineQuantity: "Cantidad",
  lineUnit: "Unidad",
  lineDescription: "Descripción",
  linesCount: (n: number) => `${n} líneas`,
  awaitingScheduleBadge: "Por programar",
  hasWorks: (n: number) => `${n} en planta`,
  noWorks: "—",
  edit: "Editar",
  validation: {
    client: "Seleccione un cliente.",
    lines: "Agregue al menos una línea con producto y cantidad.",
    quantity: "Indique una cantidad mayor a cero.",
    product: "Seleccione un producto.",
    productClient: "El producto no pertenece al cliente seleccionado.",
    onlyOpen: "Solo puede editar órdenes abiertas.",
  },
} as const

/** @deprecated Use PRODUCTION_ORDER_LABELS */
export const NROC_ORDER_LABELS = PRODUCTION_ORDER_LABELS

const STATUS_ES: Record<string, string> = {
  open: "Abierta",
  fulfilled: "Cerrada",
  cancelled: "Anulada",
}

export function productionOrderStatusLabel(status: string): string {
  return STATUS_ES[status] ?? status
}

/** @deprecated Use productionOrderStatusLabel */
export const nrocOrderStatusLabel = productionOrderStatusLabel
