export const SUPPLIER_LABELS = {
  listTitle: "Proveedores",
  listSubtitle: "Proveedores usados en compras y órdenes de compra.",
  formNewTitle: "Nuevo proveedor",
  formEditTitle: "Editar proveedor",
  formSubtitle: "Datos de identificación y contacto del proveedor.",
  formFooterHint: "Indique al menos el nombre del proveedor.",
  sections: {
    identity: "Identificación",
    identityHint: "Nombre y RIF del proveedor.",
    contact: "Contacto",
    contactHint: "Correo, teléfono y dirección fiscal o de entrega.",
  },
  preview: {
    title: "Vista previa",
    hint: "Este proveedor estará disponible en órdenes de compra.",
  },
  validation: {
    name: "Indique el nombre del proveedor.",
    rifRequired: "Si no marca «Sin RIF», debe completar el RIF.",
    phone: "Teléfono inválido. Use solo números, espacios o guiones (7–15 dígitos).",
    email: "Correo inválido.",
    summary: "Revise los campos marcados antes de guardar.",
  },
  searchLabel: "Buscar",
  searchPlaceholder: "Nombre o RIF…",
  newSupplier: "Nuevo proveedor",
  save: "Guardar",
  saving: "Guardando…",
  cancel: "Volver",
  emptyTitle: "Sin proveedores",
  emptyInactiveTitle: "Sin proveedores desactivados",
  emptyInactiveDescription: "Los proveedores desactivados aparecerán aquí.",
  emptyFiltered: "Sin resultados",
  emptyDescription: "Crea el primero para gestionar órdenes de compra.",
  emptyFilteredDescription: "Prueba otro término de búsqueda.",
  loadError: "No se pudo cargar la lista de proveedores.",
  saveError: "No se pudo guardar el proveedor.",
  saved: "Proveedor guardado.",
  savedEdit: "Proveedor actualizado.",
  loadOneError: "No se pudo cargar el proveedor.",
  noRif: "Sin RIF",
  fields: {
    name: "Nombre",
    rif: "RIF",
    email: "Correo",
    phone: "Teléfono",
    address: "Dirección",
    created: "Creado",
  },
  table: {
    number: "N.º",
    actions: "Acciones",
    edit: "Editar",
  },
  tabs: {
    active: "Activos",
    inactive: "Desactivados",
  },
  status: {
    active: "Activo",
    inactive: "Inactivo",
  },
  actions: {
    deactivate: "Desactivar",
    activate: "Activar",
  },
  toggleActivated: "Proveedor activado.",
  toggleDeactivated: "Proveedor desactivado.",
  toggleError: "No se pudo actualizar el estado del proveedor.",
  count: (n: number) =>
    n === 1 ? "1 proveedor" : `${n.toLocaleString("es-VE")} proveedores`,
} as const
