export const DISPATCH_LABELS = {
  title: "Despacho",
  subtitle: "Armar paletas con bobinas producidas y generar nota de despacho.",
  helpFlow:
    "1) Bobinas: paletas (peso manual). 2) Bolsones/desperdicio: envíe desde Inventario y dé salida aquí cuando ya no estén en planta.",
  sections: {
    bobinas: "Inventario de bobinas",
    bobinasHint:
      "Cantidad de bobinas por orden de producción. El peso en kg se ingresa manualmente al armar la paleta.",
    bolsonesInDispatch: "Bolsones en despacho",
    bolsonesInDispatchHint: "Retire cuando salgan de planta — no quedan en despacho para siempre.",
    desperdicioInDispatch: "Desperdicio en despacho",
    desperdicioInDispatchHint: "Retire cuando salgan de planta — no queda en despacho para siempre.",
    pallet: "Armar paleta",
    palletHint: "Datos comerciales, pesos por bobina e impresión de listas y etiquetas.",
    confirm: "Confirmar despacho",
    confirmHint: "Registra las paletas armadas en el historial de despachos.",
    history: "Historial de despachos",
    historyHint: "Paletas ya confirmadas. Puede reimprimir documentación.",
    outboundRegistry: "Historial de despachos",
    outboundRegistryHint:
      "Paletas ya confirmadas: fecha, cliente, bobinas, turno y destino. Filtre por fecha y reimprima etiquetas o listas.",
    lastBatch: "Despacho registrado",
    lastBatchHint: "Imprima la lista de empaque con las paletas de este lote.",
  },
  placeholders: {
    clientName: "Ej. Distribuidora La Planta C.A.",
    destination: "Ej. Valencia, planta cliente",
    productName: "Ej. MICROPERFORADO transparente",
    measurements: "Ej. 1080X0.65",
    notes: "Ej. Entrega urgente, gate 3…",
    coilWeight: "kg",
    coilShift: "Turno",
  },
  assignToPallet: "Asignar a paleta activa",
  stepBobinas: "Bobinas disponibles",
  stepPallet: "Armar paleta",
  stepConfirm: "Confirmar",
  clientName: "Cliente",
  destination: "Destino",
  productName: "Producto",
  measurements: "Medidas",
  notes: "Notas",
  selectBobinas: "Seleccione bobinas para la paleta",
  bobinaSelectHint: "Seleccione las bobinas por número. El peso de cada una se ingresa manualmente al armar la paleta.",
  noBobinas: "No hay bobinas disponibles. Registre extrusión primero.",
  inventorySummary: (orderCount: number, coilCount: number) =>
    `${orderCount} ${orderCount === 1 ? "orden" : "órdenes"} · ${coilCount} ${coilCount === 1 ? "bobina" : "bobinas"}`,
  orderGroupBobinas: (count: number) =>
    `${count} ${count === 1 ? "bobina" : "bobinas"}`,
  subproductsLinkBolsones: "Inventario bolsones",
  subproductsLinkDesperdicio: "Inventario desperdicio",
  filteredWorkHint: (workOrderId: number) =>
    `Mostrando bobinas del trabajo #${workOrderId}. Quite el filtro en la URL para ver todas.`,
  totalKg: "Total paleta",
  selectedCount: "Seleccionadas",
  weightGridTitle: "Turno y peso por bobina (etiqueta)",
  weightRequired: (code: string) => `Ingrese el peso neto de la bobina ${code}`,
  shiftRequired: (code: string) =>
    `Indique el turno de la bobina ${code} (aparece en la etiqueta impresa)`,
  newPallet: "Nueva paleta",
  palletsBuilt: "Paletas armadas",
  confirm: "Confirmar despacho",
  confirming: "Confirmando…",
  confirmSuccess: "Paletas registradas.",
  confirmError: "No se pudo registrar el despacho.",
  loadError: "No se pudieron cargar las bobinas.",
  previewPacking: "Vista previa lista de empaque",
  previewCoilLabels: "Vista previa etiquetas",
  printPacking: "Imprimir lista de empaque",
  printPackingList: "Imprimir lista de empaque",
  printCoilLabels: "Imprimir etiquetas de bobinas (hoja A4)",
  previewPackingList: "Vista previa lista de empaque",
  lastBatchTitle: "Despacho registrado",
  lastBatchHint: "Imprima la lista de empaque con las paletas de este lote.",
  palletInternalCode: (code: string) => `Ref. interna: ${code}`,
  historyTitle: "Historial de despachos",
  historyEmpty: "Aún no hay paletas despachadas.",
  historyLoading: "Cargando historial…",
  historyLoadError: "No se pudo cargar el historial de despachos.",
  reprintPacking: "Reimprimir lista",
  emptySelection: "Seleccione al menos una bobina.",
  historyDateFrom: "Desde",
  historyDateTo: "Hasta",
  historyApplyDates: "Filtrar",
  historyDateHint: "Filtra el historial por fecha de despacho.",
  registry: {
    title: "Historial de despachos",
    date: "Fecha",
    pallet: "Paleta",
    client: "Cliente / producto",
    coils: "Bobinas",
    shift: "Turno",
    kg: "Kg total",
    destination: "Destino",
    actions: "Acciones",
    labels: "Etiquetas",
  },
} as const
