export const CLIENT_LABELS = {
  listTitle: "Clientes",
  listSubtitle: "Catálogo de clientes del sistema.",
  formNewTitle: "Nuevo cliente",
  formEditTitle: "Editar cliente",
  formSubtitle: "Datos de identificación y contacto.",
  searchLabel: "Buscar",
  searchPlaceholder: "Nombre, RIF o ciudad…",
  searchPlaceholderInventory: "Nombre o RIF…",
  newClient: "Nuevo cliente",
  save: "Guardar",
  saving: "Guardando…",
  cancel: "Volver",
  noRif: "Sin RIF",
  sections: {
    identity: "Identificación",
    identityHint: "Nombre y documento fiscal del cliente.",
    commercial: "Comercial",
    commercialHint: "Asignación opcional del vendedor responsable.",
    location: "Ubicación",
    locationHint: "Estado y ciudad de operación.",
    contact: "Contacto",
    contactHint: "Correo, teléfono y dirección.",
  },
  emptyTitle: "Sin clientes",
  emptyFiltered: "Sin resultados",
  emptyDescription: "Crea el primero para gestionar pedidos y producción.",
  emptyFilteredDescription: "Prueba otro término de búsqueda.",
  loadError: "No se pudo cargar la lista de clientes.",
  saveError: "No se pudo guardar el cliente.",
  saved: "Cliente guardado.",
  savedEdit: "Cliente actualizado.",
  loadOneError: "No se pudo cargar el cliente.",
  fields: {
    name: "Nombre",
    rif: "RIF",
    state: "Estado",
    city: "Ciudad",
    email: "Correo",
    phone: "Teléfono",
    address: "Dirección",
    vendor: "Vendedor asignado",
    created: "Creado",
  },
  vendorSelect: "Buscar vendedor…",
  vendorOptionalHint: "Opcional. Deje vacío si el cliente no tiene vendedor asignado.",
  vendorNone: "Sin vendedor",
  table: {
    number: "N.º",
    actions: "Acciones",
    edit: "Editar",
  },
  tabs: {
    active: "Activos",
    inactive: "Desactivados",
  },
  status: {
    active: "Activo",
    inactive: "Inactivo",
  },
  actions: {
    deactivate: "Desactivar",
    activate: "Activar",
  },
  toggleActivated: "Cliente activado.",
  toggleDeactivated: "Cliente desactivado.",
  toggleError: "No se pudo actualizar el estado del cliente.",
  count: (n: number) =>
    n === 1 ? "1 cliente" : `${n.toLocaleString("es-VE")} clientes`,
  validation: {
    name: "Indique el nombre del cliente.",
    rifRequired: "Si no marca «Sin RIF», debe completar el RIF.",
    phone: "Teléfono inválido. Use solo números, espacios o guiones (7–15 dígitos).",
    email: "Correo inválido.",
    summary: "Revise los campos marcados antes de guardar.",
  },
} as const
