export const PURCHASE_RECEIPT_LABELS = {
  listTitle: "Recepción de material",
  listSubtitle: "Registro de entradas físicas contra órdenes de compra.",
  formTitle: "Nueva recepción",
  formSubtitle: "Indique factura, fecha y cantidades recibidas por línea de la OC.",
  helpFlow:
    "Registre la entrada física contra una orden de compra. El inventario se actualiza al guardar la recepción.",
  sections: {
    order: "Orden de compra",
    orderHint: "Seleccione la OC pendiente y confirme el proveedor.",
    document: "Documento de recepción",
    documentHint: "Número de factura y fecha de llegada del material.",
    notes: "Notas",
    notesHint: "Observaciones opcionales sobre la entrega.",
    lines: "Líneas recibidas",
    linesHint: "Cantidades por ítem de la OC. No supere lo pendiente.",
  },
  placeholders: {
    invoice: "Ej. F-001234",
    notes: "Ej. Entrega parcial, lote dañado en transporte…",
    quantity: "Ej. 500",
    materialEmpty: "Seleccione material…",
  },
  searchLabel: "Buscar",
  searchPlaceholder: "Proveedor, factura o material…",
  newReceipt: "Nueva recepción",
  receive: "Recibir",
  save: "Registrar recepción",
  saving: "Guardando…",
  cancel: "Cancelar",
  loadOneError: "No se pudo cargar la recepción.",
  loadPoError: "No se pudo cargar la orden de compra.",
  saveError: "No se pudo registrar la recepción.",
  duplicateWarning: "Ya existe una recepción con el mismo proveedor y número de factura.",
  loadError: "No se pudo cargar el listado.",
  tabs: {
    pending: "OC pendientes",
    history: "Historial",
  },
  emptyPendingTitle: "Sin órdenes pendientes de recepción",
  emptyPendingDescription: "Todas las órdenes activas ya tienen al menos una recepción.",
  emptyHistoryTitle: "Sin recepciones registradas",
  emptyHistoryDescription: "Cuando registre la primera entrada de material, aparecerá aquí.",
  emptyFiltered: "Sin resultados",
  emptyFilteredDescription: "Prueba otros filtros o términos de búsqueda.",
  fields: {
    receiptCode: "Recepción",
    supplier: "Proveedor",
    invoice: "N° factura",
    purchaseOrder: "Orden de compra",
    receivedAt: "Fecha recepción",
    notes: "Notas",
    material: "Material",
    itemType: "Tipo",
    quantity: "Cantidad recibida",
    pending: "Pendiente",
    unit: "Unidad",
    micras: "Micras",
    ancho: "Ancho (mm)",
    lines: "Líneas",
    user: "Registrado por",
  },
  poSelect: "Seleccione orden de compra…",
  poRequired: "Seleccione una orden de compra para recibir material.",
  invoiceRequired: "Indique el número de factura.",
  receivedAtRequired: "Indique la fecha de recepción.",
  linesMinError: "Indique al menos una línea con cantidad mayor que cero.",
  materialRequired: "Cada línea debe tener un material del catálogo.",
  qtyExceedsPending: "La cantidad no puede superar lo pendiente en la OC.",
  dimensionsRequired: "Micras y ancho son obligatorios para sustrato.",
  table: {
    number: "N.º",
    actions: "Acciones",
    view: "Ver OC",
  },
  count: (n: number) =>
    n === 1 ? "1 recepción" : `${n.toLocaleString("es-VE")} recepciones`,
  receiptCode: (id: number) => `REC-${id}`,
  filters: {
    supplier: "Proveedor",
    invoice: "N° factura",
    from: "Desde",
    to: "Hasta",
  },
} as const
