export const SUBPRODUCTS_LABELS = {
  columns: {
    order: "Orden de producción",
    client: "Cliente",
    measure: "Medida",
    stockOrigin: "Origen",
    registered: "Registrado",
    dispatched: "Enviado a despacho",
    pending: "Pendiente",
    released: "Ya salió",
    refil: "Refil",
    transparente: "Transparente",
  },
  placeholders: {
    kg: "kg a enviar",
    reason: "Motivo del envío (opcional)",
  },
  ship: "Enviar a despacho",
  shipping: "Enviando…",
  shipError: "No se pudo registrar el envío.",
  shipStepsTitle: "Cómo enviar",
  shipSteps:
    "Envíe kg a despacho desde aquí. Cuando salgan de planta, retírelos en Despacho con «Sacar de despacho».",
  columnsInDispatch: {
    inDispatch: "En despacho",
    release: "Salida",
  },
  release: "Sacar de despacho",
  releasing: "Registrando salida…",
  releaseSuccessBolsones: "Bolsones dados de salida en despacho.",
  releaseSuccessDesperdicio: "Desperdicio dado de salida en despacho.",
  releaseError: "No se pudo registrar la salida.",
  releasePlaceholder: "kg a sacar",
  releaseReason: "Motivo de salida (opcional)",
  emptyInDispatch: "No hay kg pendientes de salida en despacho.",
  exportPdf: "PDF",
  exportCsv: "CSV",
  exportXls: "Excel",
  exportPrint: "Imprimir",
  goToDispatch: "Ir a despacho de bobinas",
  filteredWorkHint: (workOrderId: number) => `Filtrando por trabajo #${workOrderId}.`,
} as const

export const BOLSONES_LABELS = {
  title: "Inventario de bolsones",
  subtitle: "Stock por medida. La producción suma kg automáticamente; también puede dar entrada manual.",
  helpFlow:
    "Cada medida es una fila de inventario (como materiales). Extrusión/sellado suman kg a su medida; también puede dar entrada manual. Luego envía a despacho.",
  empty: "No hay bolsones en inventario. Dé entrada manual arriba o registre en extrusión/sellado.",
  loadError: "No se pudo cargar el inventario de bolsones.",
  shipSuccess: "Bolsones enviados a despacho.",
  entryTitle: "Dar entrada al inventario",
  entryHint:
    "Indique medida y kg. Se acumula en la fila de esa medida, igual que el stock de materiales.",
  entryMeasure: "Medida",
  entryMeasurePlaceholder: "Ej. 80X0.65",
  entryKg: "Kg bolsones",
  entryNotes: "Observación (opcional)",
  entrySave: "Registrar entrada",
  entrySaving: "Registrando…",
  entrySuccess: "Entrada de bolsones registrada.",
  entryError: "No se pudo registrar la entrada.",
  entryValidationMeasure: "Indique la medida.",
  entryValidationKg: "Indique kg mayores a cero.",
  entryKindManual: "Entrada manual",
  sourceProduction: "Producción",
  sourceManual: "Manual",
  linkDesperdicio: "Inventario de desperdicio",
} as const

export const DESPERDICIO_LABELS = {
  title: "Inventario de desperdicio",
  subtitle: "Desperdicio de extrusión y sellado por orden. También admite entrada manual sin OP.",
  helpFlow:
    "Los kg pueden venir de extrusión/sellado o darse de entrada manualmente aquí, sin orden previa. Luego puede enviar a despacho.",
  empty: "No hay desperdicio en inventario. Dé entrada manual arriba o registre en extrusión/sellado.",
  loadError: "No se pudo cargar el inventario de desperdicio.",
  shipSuccess: "Desperdicio enviado a despacho.",
  entryTitle: "Dar entrada al inventario",
  entryHint:
    "Para desperdicio que ya existe en planta pero no está ligado a una OP. Indique descripción y kg.",
  entryDescription: "Descripción",
  entryDescriptionPlaceholder: "Ej. Refil acumulado turno noche",
  entryWasteType: "Tipo",
  entryWasteTypePlaceholder: "Seleccione refil o transparente",
  entryWasteTypeRefil: "Refil",
  entryWasteTypeTransparente: "Transparente",
  entryValidationWasteType: "Indique si es refil o transparente.",
  entryKg: "Kg desperdicio",
  entryNotes: "Observación (opcional)",
  entrySave: "Registrar entrada",
  entrySaving: "Registrando…",
  entrySuccess: "Entrada de desperdicio registrada.",
  entryError: "No se pudo registrar la entrada.",
  entryValidationDescription: "Indique una descripción.",
  entryValidationKg: "Indique kg mayores a cero.",
  linkBolsones: "Inventario de bolsones",
  extrusionNote: "Fuente: extrusión (refil/transparente), sellado o entrada manual.",
} as const

export const FALLAS_LABELS = {
  title: "Inventario de fallas",
  subtitle: "Fallas de extrusión y devoluciones verificadas. Ciclo: fallas → materiales (reciclaje).",
  helpFlow:
    "Registre fallas en extrusión o envíe devoluciones a «Fallas». Desde aquí envía kg a materiales; almacén verifica el ingreso al sustrato.",
  empty: "No hay fallas pendientes. Registre kg en extrusión o devoluciones a fallas.",
  loadError: "No se pudo cargar el inventario de fallas.",
  shipSuccess: "Fallas enviadas a materiales (pendiente de verificar).",
  shipToMaterials: "Enviar a materiales",
  accept: "Verificar ingreso",
  accepting: "Verificando…",
  acceptSuccess: "Ingreso verificado en materiales (sustrato reciclado).",
  acceptError: "No se pudo verificar el ingreso.",
  pendingMaterialsTitle: "Pendientes en materiales",
  pendingMaterialsEmpty: "No hay envíos pendientes de verificación.",
  extrusionNote: "Fuente: kg de fallas en extrusión + devoluciones aceptadas en ruta Fallas.",
  linkDesperdicio: "Inventario de desperdicio",
  linkBolsones: "Inventario de bolsones",
  linkMateriales: "Ir a materiales",
  columns: {
    extrusion: "Extrusión",
    returns: "Devoluciones",
    sentMaterials: "En materiales",
  },
} as const
