export const PRODUCT_LABELS = {
  listTitle: "Especificaciones de producto",
  listSubtitle: "Catálogo de productos por cliente (medida, micraje y composición).",
  formNewTitle: "Nueva especificación",
  formEditTitle: "Editar especificación",
  formSubtitle: "Referencia del producto con medida, micraje y composición de resinas.",
  formHelp:
    "En plástico no se usa CPE ni MPS. Complete el nombre del producto, la medida o micraje y, si aplica, la composición de la mezcla.",
  formFooterHint: "Los campos con cliente y producto son obligatorios.",
  validation: {
    client: "Seleccione un cliente.",
    name: "Indique el nombre del producto.",
    summary: "Revise los campos marcados antes de guardar.",
  },
  sections: {
    identity: "Identificación",
    identityHint: "Cliente y nombre comercial del producto.",
    specs: "Medida y composición",
    specsHint: "Micraje, medida y fórmula de resinas si aplica.",
  },
  preview: {
    title: "Vista previa",
    hint: "Esta ficha se usará al crear líneas en órdenes de producción.",
  },
  searchLabel: "Buscar",
  searchPlaceholder: "Nombre, medida o código de barras…",
  clientFilter: "Cliente",
  clientFilterAll: "Todos los clientes",
  clientSelect: "Seleccione un cliente",
  newProduct: "Nueva especificación",
  save: "Guardar",
  saving: "Guardando…",
  cancel: "Volver",
  emptyTitle: "Sin especificaciones",
  emptyFiltered: "Sin resultados",
  emptyDescription: "Crea la primera especificación para un cliente.",
  emptyFilteredDescription: "Prueba otro término o cambia el filtro de cliente.",
  loadError: "No se pudo cargar la lista de especificaciones.",
  saveError: "No se pudo guardar la especificación.",
  saved: "Especificación guardada.",
  savedEdit: "Especificación actualizada.",
  loadOneError: "No se pudo cargar la especificación.",
  fields: {
    client: "Cliente",
    name: "Producto",
    namePlaceholder: "Ej. MICROPERFORADO, C300",
    barcode: "Código de barras (opcional)",
    structure: "Medida y micraje",
    structurePlaceholder: "Ej. 80X0.65",
    structureHint:
      "Opcional: agregue la composición de resinas en la misma casilla (ej. 50%3003+25%11PG1+25%DE ALTA).",
    created: "Creado",
  },
  table: {
    number: "N.º",
    actions: "Acciones",
    edit: "Editar",
  },
  count: (n: number) =>
    n === 1 ? "1 especificación" : `${n.toLocaleString("es-VE")} especificaciones`,
} as const
