export const AREA_REQUEST_LABELS = {
  listTitle: "Solicitudes entre áreas",
  listSubtitle: "Bandeja de almacén para autorizar y despachar insumos solicitados.",
  insumosTitle: "Despacho de insumos",
  insumosSubtitle: "Revise líneas, autorice y registre la salida de inventario.",
  newRequest: "Nueva solicitud",
  viewInsumos: "Ver insumos",
  back: "Volver",
  dispatch: "Aprobar salida",
  dispatching: "Despachando…",
  loadError: "No se pudieron cargar las solicitudes.",
  loadDetailError: "No se pudo cargar la solicitud de insumos.",
  dispatchError: "No se pudo registrar el despacho.",
  dispatchSuccess: "Salida registrada. Se generó la submezcla para extrusión.",
  dispatchSuccessWithMixture: (mixtureId: number) =>
    `Salida registrada. Submezcla #${mixtureId} lista en Producción de mezclas.`,
  emptyTitle: "Sin solicitudes",
  emptyDescription: "No hay solicitudes de insumos con los filtros actuales.",
  pendingBadge: (n: number) => (n === 1 ? "1 pendiente" : `${n} pendientes`),
  fields: {
    id: "ID",
    area: "Área",
    title: "Título",
    requester: "Solicitante",
    status: "Estado",
    material: "Material (opcional)",
    requested: "Solicitado",
    dispatched: "Despachado",
    toDispatch: "A despachar",
    notes: "Observaciones",
    originatingArea: "Área origen",
    workOrder: "Trabajo en planta",
    rejectionReason: "Motivo del rechazo",
    description: "Descripción",
    unit: "Unidad",
  },
  table: {
    number: "N.º",
    requestNumber: "N.º solicitud",
    productionOrder: "N.º OP",
    actions: "Acciones",
  },
  count: (n: number) =>
    n === 1 ? "1 solicitud" : `${n.toLocaleString("es-VE")} solicitudes`,
  filters: {
    area: "Área",
    status: "Estado",
  },
  status: {
    pending: "Pendiente",
    done: "Completada",
    cancelled: "Cancelada",
  },
  materialStatus: {
    pending: "Pendiente",
    authorized: "Autorizada",
    partial: "Parcial",
    dispatched: "Despachada",
    rejected: "Rechazada",
    counter_proposed: "Contraoferta almacén",
    counter_accepted: "Contraoferta aceptada",
    counter_rejected: "Contraoferta rechazada",
    cancelled: "Cancelada",
  },
  qtyRequired: "Indique cantidad a despachar en al menos una línea.",
  qtyExceedsPending: "La cantidad supera lo pendiente en la línea.",
  noPendingLines: "No hay líneas pendientes de despacho en esta solicitud.",
  noLinesToDispatch: "No hay líneas disponibles para despacho.",
  rejectTitle: "Rechazar solicitud",
  rejectHint: "Indique el motivo. Opcionalmente proponga otra lista de materiales para que producción la revise.",
  reject: "Rechazar solicitud",
  rejecting: "Rechazando…",
  rejectError: "No se pudo rechazar la solicitud.",
  rejectSuccess: "Solicitud rechazada. Producción será notificada si hay contraoferta.",
  rejectReasonRequired: "El motivo del rechazo es obligatorio.",
  proposeCounter: "Proponer otra lista de materiales (contraoferta)",
  counterLinesTitle: "Ítems de la contraoferta",
  addCounterLine: "Agregar ítem",
  removeCounterLine: "Quitar",
  counterLinesRequired: "Agregue al menos un ítem en la contraoferta.",
  counterPendingTitle: "Esperando respuesta de producción",
  counterPendingHint: "Almacén propuso una contraoferta. Producción debe aceptarla o rechazarla antes de continuar el despacho.",
  reviewCounter: "Revisar contraoferta (producción)",
  receive: "Recibir en almacén",
  receiving: "Recibiendo…",
  receiveSuccess: "Entrada de producción registrada en almacén.",
  receiveError: "No se pudo registrar la recepción.",
  closeRequest: "Cerrar solicitud",
  closing: "Cerrando…",
  closeSuccess: "Solicitud cerrada. Ya no se pueden hacer más despachos parciales.",
  closeError: "No se pudo cerrar la solicitud.",
  inboundTitle: "Entrada desde producción",
  inboundHint: "Confirme la recepción de mezcla producida en planta.",
  dispatchMixtureHint:
    "Al aprobar la salida se crea una submezcla (misma receta, cantidades de este despacho). Producción inicia extrusión desde ahí.",
} as const
