export const PURCHASE_ORDER_LABELS = {
  listTitle: "Órdenes de compra",
  listSubtitle: "Solicitudes de material a proveedores y seguimiento de recepción.",
  formNewTitle: "Nueva orden de compra",
  formEditTitle: "Editar orden de compra",
  formViewTitle: "Orden de compra",
  formSubtitle: "Indique proveedor, código y las líneas de material solicitadas.",
  formFooterHint: "Proveedor, código y al menos una línea con cantidad son obligatorios.",
  sections: {
    header: "Datos de la orden",
    headerHint: "Proveedor, código, fecha y condiciones.",
    lines: "Líneas de material",
    linesHint: "Materiales o descripciones solicitadas al proveedor.",
  },
  preview: {
    title: "Vista previa",
    hint: "Tras guardar, podrá registrar recepciones contra esta orden.",
  },
  validation: {
    supplier: "Seleccione un proveedor.",
    code: "Indique el código de la orden.",
    changeReason: "Indique el motivo del cambio (mín. 5 caracteres).",
    summary: "Revise los campos marcados antes de guardar.",
  },
  searchLabel: "Buscar",
  searchPlaceholder: "Código de orden…",
  supplierFilter: "Proveedor",
  supplierFilterAll: "Todos los proveedores",
  newOrder: "Nueva orden",
  save: "Guardar orden",
  saving: "Guardando…",
  cancel: "Cancelar",
  loadOneError: "No se pudo cargar la orden de compra.",
  saveError: "No se pudo guardar la orden de compra.",
  tabs: {
    pending: "Pendientes",
    history: "Con recepción",
  },
  emptyPendingTitle: "Sin órdenes pendientes",
  emptyHistoryTitle: "Sin órdenes con recepción",
  emptyFiltered: "Sin resultados",
  emptyPendingDescription: "Crea una orden de compra para solicitar material a proveedores.",
  emptyHistoryDescription:
    "Cuando se registre la primera recepción de una orden, pasará a esta pestaña.",
  emptyFilteredDescription: "Prueba otro código o cambia el filtro de proveedor.",
  loadError: "No se pudo cargar la lista de órdenes de compra.",
  fields: {
    code: "Código",
    supplier: "Proveedor",
    status: "Estado",
    progress: "Recibido / Pedido",
    lines: "Líneas",
    receipts: "Recepciones",
    orderedAt: "Fecha pedido",
    created: "Creado",
    notes: "Notas",
    taxApplies: "Aplica impuesto",
    changeReason: "Motivo del cambio",
    material: "Material",
    description: "Descripción",
    quantity: "Cantidad",
    unit: "Unidad",
    unitPrice: "Precio unitario",
  },
  supplierSelect: "Seleccione proveedor…",
  materialSelect: "Sin material (texto libre)",
  changeReasonHint: "Obligatorio al modificar una orden existente (mín. 5 caracteres).",
  linesSection: "Líneas de material",
  addLine: "Agregar línea",
  removeLine: "Quitar",
  linesMinError: "Agregue al menos una línea con cantidad.",
  table: {
    number: "N.º",
    actions: "Acciones",
    view: "Ver",
    edit: "Editar",
  },
  count: (n: number) =>
    n === 1 ? "1 orden" : `${n.toLocaleString("es-VE")} órdenes`,
} as const
