export const MATERIAL_LABELS = {
  listTitle: "Materiales",
  listSubtitle:
    "Inventario de insumos por categoría: resina, pigmento, misceláneo y deslizante.",
  formNewTitle: "Nuevo material",
  formEditTitle: "Editar material",
  formSubtitle:
    "Registro manual de insumo. Para carga masiva use la plantilla Excel en la lista.",
  helpFlow:
    "Registro manual de insumo. Para carga masiva use la plantilla Excel en la lista de materiales.",
  sections: {
    classification: "Clasificación",
    classificationHint: "Categoría, tipo y marca generan el código automáticamente.",
    stock: "Stock inicial",
    stockHint: "Cantidad en kg y sacos (25 kg por saco).",
    entry: "Datos de entrada",
    entryHint: "Opcional al crear; se completan al registrar una recepción.",
    notes: "Notas",
    notesHint: "Información adicional del material.",
    audit: "Auditoría",
    auditHint: "Obligatorio si modifica datos críticos del material.",
  },
  placeholders: {
    quantityKg: "Ej. 1250",
    unitsCount: "Ej. 50",
    containerNumber: "Ej. CONT-2024-001",
    notes: "Ej. Ubicación en almacén, lote preferido…",
    changeReason: "Ej. Corrección de marca registrada…",
  },
  searchLabel: "Buscar",
  searchPlaceholder: "Tipo, marca o categoría…",
  newMaterial: "Nuevo material",
  save: "Guardar",
  saving: "Guardando…",
  cancel: "Cancelar",
  loadOneError: "No se pudo cargar el material.",
  saveError: "No se pudo guardar el material.",
  loadError: "No se pudo cargar la lista de materiales.",
  emptyTitle: "Sin materiales en inventario",
  emptyDescription:
    "Descarga la plantilla Excel, complétala con el almacén e impórtala para cargar el stock.",
  emptyFiltered: "Sin resultados",
  emptyFilteredDescription: "Prueba otro término o cambia el filtro de categoría.",
  fields: {
    sku: "Código",
    productType: "Tipo",
    brand: "Marca",
    category: "Categoría",
    name: "Nombre",
    barcode: "Código de barras",
    area: "Categoría",
    subarea: "Subárea (mezclas)",
    micras: "Micras",
    ancho: "Ancho (mm)",
    unit: "Unidad",
    stock: "Stock (kg)",
    quantityKg: "Cantidad (kg)",
    unitsCount: "Sacos (25 kg c/u)",
    containerNumber: "Nº contenedor",
    minStock: "Stock mínimo",
    supplier: "Proveedor",
    noSupplierReason: "Motivo sin proveedor",
    notes: "Notas",
    changeReason: "Motivo del cambio",
    created: "Creado",
  },
  hints: {
    sacoWeight: "Cada saco equivale a 25 kg.",
    entryFields: "Proveedor y nº de contenedor se completan al registrar la entrada.",
    skuAuto: "Se genera de tipo, marca y nº de contenedor (mismo producto en otro contenedor = otro código).",
  },
  supplierNone: "Sin proveedor",
  supplierSelect: "Seleccione proveedor…",
  table: {
    number: "N.º",
    actions: "Acciones",
    edit: "Editar",
  },
  templates: {
    downloadInitial: "Descargar plantilla",
    importExcel: "Importar Excel",
  },
  import: {
    title: "Importar inventario",
    subtitle: "Carga masiva desde plantilla CSV/Excel con stock actual del almacén.",
    instructions:
      "Use la plantilla con columnas Fecha, Categoría, Tipo, Marca, Cantidad_kg, Unidades_sacos, Proveedor y Nro_contenedor. Proveedor y contenedor pueden ir vacíos en la carga inicial.",
    dropTitle: "Arrastre el archivo o selecciónelo",
    dropHint: "CSV o Excel (.csv, .xlsx). Guarde la plantilla como CSV UTF-8 si usa Excel.",
    selectFile: "Seleccionar archivo",
    confirm: "Importar al inventario",
    importing: "Importando…",
    changeFile: "Cambiar archivo",
    emptyFile: "El archivo no tiene filas de datos.",
    parseError: "No se pudo leer el archivo.",
    noValidRows: "No hay filas válidas para importar.",
    importError: "No se pudo importar el inventario.",
    previewCount: (n: number) =>
      n === 1 ? "1 fila en vista previa" : `${n.toLocaleString("es-VE")} filas en vista previa`,
    fileSummary: (valid: number, invalid: number) =>
      `${valid.toLocaleString("es-VE")} válidas · ${invalid.toLocaleString("es-VE")} con error`,
    success: (r: { created: number; updated: number }) =>
      `Importación lista: ${r.created} nuevos, ${r.updated} actualizados.`,
    partialSuccess: (r: { created: number; updated: number; skipped: number }) =>
      `Importados ${r.created + r.updated}; ${r.skipped} filas omitidas.`,
    resultTitle: "Importación completada",
    resultSummary: (r: { created: number; updated: number; skipped: number; filename: string }) =>
      `${r.filename}: ${r.created} creados, ${r.updated} actualizados, ${r.skipped} omitidos.`,
    goToList: "Ver materiales",
  },
  count: (n: number) =>
    n === 1 ? "1 material" : `${n.toLocaleString("es-VE")} materiales`,
  changeReasonHint: "Obligatorio si modifica datos críticos del material.",
} as const
