export const REPORTS_LABELS = {
  title: "Reportes",
  subtitle: "Análisis de planta: tiempos, consumo de mezclas, producción de extrusión y desperdicio.",
  apply: "Aplicar",
  exportPdf: "PDF",
  exportCsv: "CSV",
  exportXls: "XLS",
  exportGroup: "Exportar",
  periodLabel: "Período",
  loading: "Cargando reporte…",
  loadError: "No se pudo cargar el reporte.",
  loadErrorHint: "Revise la conexión e intente de nuevo. Si el problema continúa, avise a soporte.",
  retry: "Reintentar",
  fromDate: "Desde",
  toDate: "Hasta",
  periodHint: "Filtra por rango de fechas y exporta el reporte en PDF, CSV o XLS.",
  recordCount: (n: number) => `${n.toLocaleString("es-VE")} registro${n === 1 ? "" : "s"}`,
  wasteConsolidated: "Total consolidado del período",
  tabs: {
    times: {
      label: "Tiempos",
      title: "Reporte de tiempo",
      description:
        "Tiempo efectivo acumulado por trabajo: suma de cada «Registrar producción» en extrusión (tramos).",
      empty: "No hay tiempos registrados en el período. Complete extrusión para ver horas efectivas.",
      accent: "violet" as const,
    },
    total: {
      label: "Consumo total",
      title: "Material consumido en planta",
      description: "Suma de kg por mezcla (componentes de recetas) en el rango seleccionado.",
      empty: "No hay mezclas registradas en el período. Cree recetas en Mezcla.",
      accent: "emerald" as const,
    },
    byOrder: {
      label: "Por orden",
      title: "Consumible por orden de producción",
      description:
        "Desglose por pedido: kg de producto extruido, mezcla utilizada en extrusión (incluye cruces) y detalle por submezcla.",
      empty: "No hay órdenes con mezclas vinculadas. Programe y registre mezclas por trabajo.",
      accent: "amber" as const,
    },
    production: {
      label: "Producción general",
      title: "Producción de extrusión",
      description:
        "Bobinas y kg en bolsones por trabajo (solo consulta). Para enviar bolsones a despacho use Producción → Inventario bolsones.",
      empty: "No hay extrusión cerrada en el período. Registre producción en Extrusión.",
      accent: "sky" as const,
    },
    waste: {
      label: "Desperdicio",
      title: "Desperdicio por orden",
      description:
        "Refil y transparente por OP (solo consulta). Para enviar kg a despacho use Producción → Inventario desperdicio.",
      empty: "No hay desperdicio registrado en el período. Indíquelo al finalizar extrusión.",
      accent: "rose" as const,
    },
    machine: {
      label: "Por máquina",
      title: "Producción por máquina y turno",
      description: "Cuadro por línea con turnos, órdenes de producción, kg y bobinas.",
      empty: "No hay tramos de extrusión en el período seleccionado.",
      accent: "violet" as const,
    },
  },
  columns: {
    machine: "Máquina / línea",
    shift: "Turno",
    work: "Trabajo",
    client: "Cliente",
    order: "Orden",
    effective: "Tiempo efectivo",
    effectiveHint: "Suma de tramos registrados en extrusión.",
    segments: "Tramos",
    dead: "Tiempo muerto",
    utilization: "% utilización",
    sku: "SKU",
    name: "Mezcla",
    totalKg: "Total kg",
    product: "Producto",
    produced: "Producido kg",
    orderTarget: "Pedido cliente kg",
    orderLines: "Líneas del pedido",
    orderLineProduct: "Producto / línea",
    orderLineQty: "Cantidad pedida",
    kgRemaining: "Faltan para culminar",
    kgRemainingHint: "Pedido del cliente menos lo ya extruido en planta.",
    orderCompleted: "Pedido completado",
    completedOrdersOnly: "Solo pedidos completados",
    completedOrdersHint: "Muestra órdenes cuyo kg extruido ya cubre el pedido del cliente.",
    completedOrdersCount: (n: number) =>
      n === 1 ? "1 pedido completado" : `${n.toLocaleString("es-VE")} pedidos completados`,
    mixtureUsed: "Mezcla utilizada kg",
    mixtureCrossIn: (kg: string) => `Incluye mezcla de otras OP: ${kg}`,
    mixtureCrossOut: (kg: string) => `Mezcla usada en otras OP: ${kg}`,
    mixtureUsedHint: "Consumo en extrusión (producto + desperdicio + core + bolsones).",
    mixtureRecipeTitle: "Receta de la mezcla (materiales)",
    mixtureRecipeHint: "Materiales y kg de la mezcla principal, como en inventario/solicitudes.",
    mixtureComponentsTitle: "Contiene",
    pendingClose: (kg: string) => `Pendiente de cierre: ${kg} (extrusión en curso)`,
    materialSku: "SKU material",
    materialName: "Material",
    materialKg: "Kg material",
    coils: "Bobinas",
    bolsones: "Kg bolsones",
    refil: "Refil kg",
    transparente: "Transparente kg",
    wasteTotal: "Total desperdicio",
  },
} as const

export type ReportTabId = keyof typeof REPORTS_LABELS.tabs
